title: That Dev Girl
production_url: http://www.thatdevgirl.com
twitter_username: jonihalabi

icons: '/assets/icons'
images: '/assets/images'

sass_dir: '/assets/_sass'
sass:
  style: compressed

include: ['_pages']
permalink: /blog/:title
highlighter: rouge
