title: That Dev Girl
description: A technical blog about website development, plugin creations, and other tech tips.
author: Joni Halabi
production_url: https://thatdevgirl.com
twitter_username: jonihalabi

icons: '/assets/icons'
images: '/assets/images'

sass_dir: '/assets/_sass'
sass:
  style: compressed

include: ['_pages']
permalink: /blog/:title
highlighter: rouge

plugins:
  - 'jekyll-feed'
